//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBP.HOME.Boilerpate.Cultures {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cultures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cultures() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BBP.HOME.Boilerpate.Cultures.Cultures", typeof(Cultures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : The application can&apos;t find a Ghostscript installation on the usual paths. The application will now continue, but the model&apos;s htlml images may not be produced..
        /// </summary>
        public static string ALERT_GHOSTSCRIPT {
            get {
                return ResourceManager.GetString("ALERT_GHOSTSCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ghostcript Alert.
        /// </summary>
        public static string ALERT_GHOSTSCRIPT_TITLE {
            get {
                return ResourceManager.GetString("ALERT_GHOSTSCRIPT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings error.
        /// </summary>
        public static string ALERT_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("ALERT_SETTINGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dymola Documentation Converter.
        /// </summary>
        public static string APPLICATION_TITLE {
            get {
                return ResourceManager.GetString("APPLICATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All contained Models.
        /// </summary>
        public static string BUTTON_ALL {
            get {
                return ResourceManager.GetString("BUTTON_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string BUTTON_CREATE {
            get {
                return ResourceManager.GetString("BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current package.
        /// </summary>
        public static string BUTTON_CURRENT_MODEL {
            get {
                return ResourceManager.GetString("BUTTON_CURRENT_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string BUTTON_DELETE {
            get {
                return ResourceManager.GetString("BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit in VSCode.
        /// </summary>
        public static string BUTTON_EDIT {
            get {
                return ResourceManager.GetString("BUTTON_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go To md Folder.
        /// </summary>
        public static string BUTTON_FOLDER {
            get {
                return ResourceManager.GetString("BUTTON_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Documentation.
        /// </summary>
        public static string BUTTON_GENERATE_DOCUMENTATION {
            get {
                return ResourceManager.GetString("BUTTON_GENERATE_DOCUMENTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libraries Folder.
        /// </summary>
        public static string BUTTON_LIB_FOLDER {
            get {
                return ResourceManager.GetString("BUTTON_LIB_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you realy  want to delete this document.
        /// </summary>
        public static string CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete document.
        /// </summary>
        public static string CONFIRM_DELETE_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to generate this file.
        /// </summary>
        public static string CONFIRM_GENERATE {
            get {
                return ResourceManager.GetString("CONFIRM_GENERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Dialog.
        /// </summary>
        public static string CONFIRM_GENERATE_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_GENERATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want this action to be done on the package  ?.
        /// </summary>
        public static string CONFIRM_GROUPED {
            get {
                return ResourceManager.GetString("CONFIRM_GROUPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Package action.
        /// </summary>
        public static string CONFIRM_GROUPED_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_GROUPED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while launching file : .
        /// </summary>
        public static string ERROR_LAUNCH {
            get {
                return ResourceManager.GetString("ERROR_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error Launch.
        /// </summary>
        public static string ERROR_LAUNCH_TITLE {
            get {
                return ResourceManager.GetString("ERROR_LAUNCH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Root can&apos;t be modified.
        /// </summary>
        public static string ERROR_ROOT {
            get {
                return ResourceManager.GetString("ERROR_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Root Action.
        /// </summary>
        public static string ERROR_ROOT_TITLE {
            get {
                return ResourceManager.GetString("ERROR_ROOT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verify your app config file. View logs for more informations..
        /// </summary>
        public static string ERROR_SETTINGS {
            get {
                return ResourceManager.GetString("ERROR_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview file.
        /// </summary>
        public static string LABEL_PREVIEW {
            get {
                return ResourceManager.GetString("LABEL_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string MENU_ABOUT {
            get {
                return ResourceManager.GetString("MENU_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string MENU_CLOSE {
            get {
                return ResourceManager.GetString("MENU_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Library Folder.
        /// </summary>
        public static string MENU_LIB {
            get {
                return ResourceManager.GetString("MENU_LIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Markdown Folder.
        /// </summary>
        public static string MENU_MD {
            get {
                return ResourceManager.GetString("MENU_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temp Folder.
        /// </summary>
        public static string MENU_TEMP {
            get {
                return ResourceManager.GetString("MENU_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Guide.
        /// </summary>
        public static string MENU_USER_GUIDE {
            get {
                return ResourceManager.GetString("MENU_USER_GUIDE", resourceCulture);
            }
        }
    }
}
